package repositories

// Generated from frontend/src/lib/localization.ts (UZBEK_GENRE_MAP and
// UZBEK_COUNTRY_MAP): English name -> Uzbek label, both lowercase. Used to
// compare titles whose genre/country were stored in either language.

var genreEnToUz = map[string]string{
	"action":          "jangari",
	"adventure":       "sarguzasht",
	"animation":       "multifilmlar",
	"anime":           "anime",
	"comedy":          "komediya",
	"crime":           "jinoyat",
	"documentary":     "hujjatli",
	"dorama":          "dorama",
	"drama":           "drama",
	"family":          "oila",
	"fantasy":         "fantastika",
	"history":         "tarixiy",
	"horror":          "dahshat",
	"kids":            "bolalar",
	"music":           "musiqa",
	"mystery":         "sirli",
	"news":            "yangiliklar",
	"romance":         "romantika",
	"science fiction": "ilmiy fantastika",
	"sci-fi":          "ilmiy fantastika",
	"soap":            "serial",
	"talk":            "talk-shou",
	"thriller":        "triller",
	"tv movie":        "tv film",
	"war":             "urush",
	"western":         "vestern",
	"cartoon":         "multifilmlar",
}

var countryEnToUz = map[string]string{
	"afghanistan":              "afg'oniston",
	"albania":                  "albaniya",
	"algeria":                  "jazoir",
	"argentina":                "argentina",
	"armenia":                  "armaniston",
	"australia":                "avstraliya",
	"austria":                  "avstriya",
	"azerbaijan":               "ozarbayjon",
	"bahamas":                  "bagama orollari",
	"bahrain":                  "bahrayn",
	"bangladesh":               "bangladesh",
	"belgium":                  "belgiya",
	"bolivia":                  "boliviya",
	"bosnia and herzegovina":   "bosniya va gertsogovina",
	"brazil":                   "braziliya",
	"bulgaria":                 "bolgariya",
	"cambodia":                 "kambodja",
	"cameroon":                 "kamerun",
	"canada":                   "kanada",
	"chile":                    "chili",
	"china":                    "xitoy",
	"colombia":                 "kolumbiya",
	"costa rica":               "kosta rika",
	"croatia":                  "xorvatiya",
	"cuba":                     "kuba",
	"czech republic":           "chexiya",
	"czechia":                  "chexiya",
	"denmark":                  "daniya",
	"dominican republic":       "dominikan respublikasi",
	"ecuador":                  "ekvador",
	"egypt":                    "misr",
	"el salvador":              "salvador",
	"estonia":                  "estoniya",
	"finland":                  "finlandiya",
	"france":                   "fransiya",
	"georgia":                  "gruziya",
	"germany":                  "germaniya",
	"ghana":                    "gana",
	"greece":                   "gretsiya",
	"guatemala":                "gvatemala",
	"haiti":                    "gaiti",
	"honduras":                 "gonduras",
	"hong kong":                "gonkong",
	"hungary":                  "vengriya",
	"iceland":                  "islandiya",
	"india":                    "hindiston",
	"indonesia":                "indoneziya",
	"iran":                     "eron",
	"iraq":                     "iroq",
	"ireland":                  "irlandiya",
	"israel":                   "isroil",
	"italy":                    "italiya",
	"jamaica":                  "yamayka",
	"japan":                    "yaponiya",
	"jordan":                   "iordaniya",
	"kazakhstan":               "qozog'iston",
	"kenya":                    "keniya",
	"north korea":              "shimoliy koreya",
	"south korea":              "janubiy koreya",
	"kuwait":                   "quvayt",
	"latvia":                   "latviya",
	"lebanon":                  "livan",
	"libya":                    "liviya",
	"lithuania":                "litva",
	"luxembourg":               "lyuksemburg",
	"malaysia":                 "malayziya",
	"malta":                    "malta",
	"mexico":                   "meksika",
	"moldova":                  "moldova",
	"monaco":                   "monako",
	"mongolia":                 "mongoliya",
	"morocco":                  "marokash",
	"nepal":                    "nepal",
	"netherlands":              "niderlandiya",
	"new zealand":              "yangi zelandiya",
	"nicaragua":                "nikaragua",
	"nigeria":                  "nigeriya",
	"norway":                   "norvegiya",
	"oman":                     "ummon",
	"pakistan":                 "pokiston",
	"palestine":                "falastin",
	"panama":                   "panama",
	"paraguay":                 "paragvay",
	"peru":                     "peru",
	"philippines":              "filippin",
	"poland":                   "polsha",
	"portugal":                 "portugaliya",
	"puerto rico":              "puerto-riko",
	"qatar":                    "qatar",
	"romania":                  "ruminiya",
	"russia":                   "rossiya",
	"russian federation":       "rossiya",
	"saudi arabia":             "saudiya arabistoni",
	"senegal":                  "senegal",
	"serbia":                   "serbiya",
	"singapore":                "singapur",
	"slovakia":                 "slovakiya",
	"slovenia":                 "sloveniya",
	"south africa":             "janubiy afrika",
	"spain":                    "ispaniya",
	"sri lanka":                "shri lanka",
	"sweden":                   "shvetsiya",
	"switzerland":              "shveytsariya",
	"syria":                    "suriya",
	"taiwan":                   "tayvan",
	"thailand":                 "tailand",
	"tunisia":                  "tunis",
	"turkey":                   "turkiya",
	"ukraine":                  "ukraina",
	"united arab emirates":     "birlashgan arab amirliklari",
	"united kingdom":           "buyuk britaniya",
	"united states of america": "amerika qo'shma shtatlari",
	"united states":            "amerika qo'shma shtatlari",
	"usa":                      "amerika qo'shma shtatlari",
	"us":                       "amerika qo'shma shtatlari",
	"uk":                       "buyuk britaniya",
	"uzbekistan":               "o'zbekiston",
	"korea":                    "janubiy koreya",
	"republic of korea":        "janubiy koreya",
	"kyrgyzstan":               "qirg'iziston",
	"tajikistan":               "tojikiston",
	"turkmenistan":             "turkmaniston",
	"uruguay":                  "urugvay",
	"venezuela":                "venesuela",
	"vietnam":                  "vyetnam",
	"yemen":                    "yaman",
	"zimbabwe":                 "zimbabve",
}
