brotli on;
brotli_comp_level 5;
brotli_types text/plain text/css application/json application/javascript text/javascript application/xml application/rss+xml image/svg+xml application/x-font-ttf font/opentype;
